package com.shinetech.mvp.DB.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shinetech.mvp.DB.bean.BaseOrderInfoDB;
import com.shinetech.mvp.DB.bean.CarInfoDB;
import com.shinetech.mvp.DB.bean.CreateMaintenanceInfoDB;
import com.shinetech.mvp.DB.bean.InstallOrderBaseInfo;
import com.shinetech.mvp.DB.bean.InstallTerminalnfo;
import com.shinetech.mvp.DB.bean.MaintenanceOrderInfoBean;
import com.shinetech.mvp.DB.bean.MaintenanceOrderProgressBean;
import com.shinetech.mvp.DB.bean.PushMessage;
import com.shinetech.mvp.DB.bean.SelectCarList;

import com.shinetech.mvp.DB.greendao.BaseOrderInfoDBDao;
import com.shinetech.mvp.DB.greendao.CarInfoDBDao;
import com.shinetech.mvp.DB.greendao.CreateMaintenanceInfoDBDao;
import com.shinetech.mvp.DB.greendao.InstallOrderBaseInfoDao;
import com.shinetech.mvp.DB.greendao.InstallTerminalnfoDao;
import com.shinetech.mvp.DB.greendao.MaintenanceOrderInfoBeanDao;
import com.shinetech.mvp.DB.greendao.MaintenanceOrderProgressBeanDao;
import com.shinetech.mvp.DB.greendao.PushMessageDao;
import com.shinetech.mvp.DB.greendao.SelectCarListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseOrderInfoDBDaoConfig;
    private final DaoConfig carInfoDBDaoConfig;
    private final DaoConfig createMaintenanceInfoDBDaoConfig;
    private final DaoConfig installOrderBaseInfoDaoConfig;
    private final DaoConfig installTerminalnfoDaoConfig;
    private final DaoConfig maintenanceOrderInfoBeanDaoConfig;
    private final DaoConfig maintenanceOrderProgressBeanDaoConfig;
    private final DaoConfig pushMessageDaoConfig;
    private final DaoConfig selectCarListDaoConfig;

    private final BaseOrderInfoDBDao baseOrderInfoDBDao;
    private final CarInfoDBDao carInfoDBDao;
    private final CreateMaintenanceInfoDBDao createMaintenanceInfoDBDao;
    private final InstallOrderBaseInfoDao installOrderBaseInfoDao;
    private final InstallTerminalnfoDao installTerminalnfoDao;
    private final MaintenanceOrderInfoBeanDao maintenanceOrderInfoBeanDao;
    private final MaintenanceOrderProgressBeanDao maintenanceOrderProgressBeanDao;
    private final PushMessageDao pushMessageDao;
    private final SelectCarListDao selectCarListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseOrderInfoDBDaoConfig = daoConfigMap.get(BaseOrderInfoDBDao.class).clone();
        baseOrderInfoDBDaoConfig.initIdentityScope(type);

        carInfoDBDaoConfig = daoConfigMap.get(CarInfoDBDao.class).clone();
        carInfoDBDaoConfig.initIdentityScope(type);

        createMaintenanceInfoDBDaoConfig = daoConfigMap.get(CreateMaintenanceInfoDBDao.class).clone();
        createMaintenanceInfoDBDaoConfig.initIdentityScope(type);

        installOrderBaseInfoDaoConfig = daoConfigMap.get(InstallOrderBaseInfoDao.class).clone();
        installOrderBaseInfoDaoConfig.initIdentityScope(type);

        installTerminalnfoDaoConfig = daoConfigMap.get(InstallTerminalnfoDao.class).clone();
        installTerminalnfoDaoConfig.initIdentityScope(type);

        maintenanceOrderInfoBeanDaoConfig = daoConfigMap.get(MaintenanceOrderInfoBeanDao.class).clone();
        maintenanceOrderInfoBeanDaoConfig.initIdentityScope(type);

        maintenanceOrderProgressBeanDaoConfig = daoConfigMap.get(MaintenanceOrderProgressBeanDao.class).clone();
        maintenanceOrderProgressBeanDaoConfig.initIdentityScope(type);

        pushMessageDaoConfig = daoConfigMap.get(PushMessageDao.class).clone();
        pushMessageDaoConfig.initIdentityScope(type);

        selectCarListDaoConfig = daoConfigMap.get(SelectCarListDao.class).clone();
        selectCarListDaoConfig.initIdentityScope(type);

        baseOrderInfoDBDao = new BaseOrderInfoDBDao(baseOrderInfoDBDaoConfig, this);
        carInfoDBDao = new CarInfoDBDao(carInfoDBDaoConfig, this);
        createMaintenanceInfoDBDao = new CreateMaintenanceInfoDBDao(createMaintenanceInfoDBDaoConfig, this);
        installOrderBaseInfoDao = new InstallOrderBaseInfoDao(installOrderBaseInfoDaoConfig, this);
        installTerminalnfoDao = new InstallTerminalnfoDao(installTerminalnfoDaoConfig, this);
        maintenanceOrderInfoBeanDao = new MaintenanceOrderInfoBeanDao(maintenanceOrderInfoBeanDaoConfig, this);
        maintenanceOrderProgressBeanDao = new MaintenanceOrderProgressBeanDao(maintenanceOrderProgressBeanDaoConfig, this);
        pushMessageDao = new PushMessageDao(pushMessageDaoConfig, this);
        selectCarListDao = new SelectCarListDao(selectCarListDaoConfig, this);

        registerDao(BaseOrderInfoDB.class, baseOrderInfoDBDao);
        registerDao(CarInfoDB.class, carInfoDBDao);
        registerDao(CreateMaintenanceInfoDB.class, createMaintenanceInfoDBDao);
        registerDao(InstallOrderBaseInfo.class, installOrderBaseInfoDao);
        registerDao(InstallTerminalnfo.class, installTerminalnfoDao);
        registerDao(MaintenanceOrderInfoBean.class, maintenanceOrderInfoBeanDao);
        registerDao(MaintenanceOrderProgressBean.class, maintenanceOrderProgressBeanDao);
        registerDao(PushMessage.class, pushMessageDao);
        registerDao(SelectCarList.class, selectCarListDao);
    }
    
    public void clear() {
        baseOrderInfoDBDaoConfig.clearIdentityScope();
        carInfoDBDaoConfig.clearIdentityScope();
        createMaintenanceInfoDBDaoConfig.clearIdentityScope();
        installOrderBaseInfoDaoConfig.clearIdentityScope();
        installTerminalnfoDaoConfig.clearIdentityScope();
        maintenanceOrderInfoBeanDaoConfig.clearIdentityScope();
        maintenanceOrderProgressBeanDaoConfig.clearIdentityScope();
        pushMessageDaoConfig.clearIdentityScope();
        selectCarListDaoConfig.clearIdentityScope();
    }

    public BaseOrderInfoDBDao getBaseOrderInfoDBDao() {
        return baseOrderInfoDBDao;
    }

    public CarInfoDBDao getCarInfoDBDao() {
        return carInfoDBDao;
    }

    public CreateMaintenanceInfoDBDao getCreateMaintenanceInfoDBDao() {
        return createMaintenanceInfoDBDao;
    }

    public InstallOrderBaseInfoDao getInstallOrderBaseInfoDao() {
        return installOrderBaseInfoDao;
    }

    public InstallTerminalnfoDao getInstallTerminalnfoDao() {
        return installTerminalnfoDao;
    }

    public MaintenanceOrderInfoBeanDao getMaintenanceOrderInfoBeanDao() {
        return maintenanceOrderInfoBeanDao;
    }

    public MaintenanceOrderProgressBeanDao getMaintenanceOrderProgressBeanDao() {
        return maintenanceOrderProgressBeanDao;
    }

    public PushMessageDao getPushMessageDao() {
        return pushMessageDao;
    }

    public SelectCarListDao getSelectCarListDao() {
        return selectCarListDao;
    }

}
